spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  flyway:
    enabled: false

logging:
  level:
    com.joseguillard.my_blog: DEBUG
    org.hibernate.SQL: DEBUG

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080
  init:
    password: ${DEV_AUTHOR_PASSWORD:sa}
    email: ${DEV_AUTHOR_EMAIL:dev@example.com}
    github: ${DEV_AUTHOR_GITHUB:https://github.com}
    linkedin: ${DEV_AUTHOR_LINKEDIN:https://linkedin.com}
    avatar-url: ${DEV_AUTHOR_AVATAR:https://recreio.com.br/noticias/entretenimento/one-piece-afinal-qual-idade-de-luffy.phtml}