spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    com.joseguillard.my_blog: INFO

app:
  init:
    password: ${STAGING_AUTHOR_PASSWORD}
    email: ${AUTHOR_EMAIL}
  cors:
    allowed-origins:
      - http://localhost:3000
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION:3600000}


